spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_test?serverTimezone=Asia/Seoul
    username: devuser
    password: 111111

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    default-models-expand-depth: -1

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.web.socket: DEBUG
    com.example.webRTC: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

  websocket:
    allowed-origins: "*"

  security:
    filter:
      order: 10
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
