spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  elasticsearch:
    uris: ${ES_URL}
  data:
    redis:
      host: ${SERVER_URL}
      port: 6379
      password: ${REDIS_PASSWORD}

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.example: DEBUG