server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  data:
    redis:
      host: ${SERVER_URL}
      port: 6379
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs